### ISSUE TITLE
some questions about TGSRec！

### ISSUE THREAD

**Issue by TangJiakai** [DyGRec/TGSRec#1]
TGSRec model is very nice and fancy, but I have some questions about your open code as follows:
1. Here, I think left should add one more, because neighbors_idx[left] must small than neighbors_idx, right?
 https://github.com/DyGRec/TGSRec/blob/9b61480db2a18a752a79f16df7bdd17c749cdd70/graph.py#L87
2.  I think this will sample some neightbors more than one time when len(ngh_idx) is smaller than num_neighbors, and I think this will lead bad influence...
https://github.com/DyGRec/TGSRec/blob/9b61480db2a18a752a79f16df7bdd17c749cdd70/graph.py#L108 
3.  why not directly use inner product but affinity_score here where I think it is not match your paper, right?
https://github.com/DyGRec/TGSRec/blob/9b61480db2a18a752a79f16df7bdd17c749cdd70/model.py#L478
4.  there is only node_hist_embed without time embedding parameter like your paper said?
https://github.com/DyGRec/TGSRec/blob/9b61480db2a18a752a79f16df7bdd17c749cdd70/run_TGREC.py#L181-L184
5. it didn't use sin but only cos, but use both of them in your paper?
 https://github.com/DyGRec/TGSRec/blob/9b61480db2a18a752a79f16df7bdd17c749cdd70/model.py#L249
6. why the matric of SYSRec、BERT4Rec etc. is so low where I think it doesnot match the ranking in https://paperswithcode.com/sota/collaborative-filtering-on-movielens-1m althogh it uses 1m not 100k dataset?
7. I think off_set_l[src_idx+1] here may happen index out of range when src_idx is max.
https://github.com/DyGRec/TGSRec/blob/9b61480db2a18a752a79f16df7bdd17c749cdd70/graph.py#L66
help me please!!!

**Comment by jeongwhanchoi** [comment]
> TGSRec model is very nice and fancy, but I have some questions about your open code as follows:
> 
>     1. Here, I think left should add one more, because neighbors_idx[left] must small than neighbors_idx, right?
>        https://github.com/DyGRec/TGSRec/blob/9b61480db2a18a752a79f16df7bdd17c749cdd70/graph.py#L87
> 
>     2. I think this will sample some neightbors more than one time when len(ngh_idx) is smaller than num_neighbors, and I think this will lead bad influence...
>        https://github.com/DyGRec/TGSRec/blob/9b61480db2a18a752a79f16df7bdd17c749cdd70/graph.py#L108
> 
>     3. why not directly use inner product but affinity_score here where I think it is not match your paper, right?
>        https://github.com/DyGRec/TGSRec/blob/9b61480db2a18a752a79f16df7bdd17c749cdd70/model.py#L478
> 
>     4. there is only node_hist_embed without time embedding parameter like your paper said?
>        https://github.com/DyGRec/TGSRec/blob/9b61480db2a18a752a79f16df7bdd17c749cdd70/run_TGREC.py#L181-L184
> 
>     5. it didn't use sin but only cos, but use both of them in your paper?
>        https://github.com/DyGRec/TGSRec/blob/9b61480db2a18a752a79f16df7bdd17c749cdd70/model.py#L249
> 
>     6. why the matric of SYSRec、BERT4Rec etc. is so low where I think it doesnot match the ranking in https://paperswithcode.com/sota/collaborative-filtering-on-movielens-1m althogh it uses 1m not 100k dataset?
> 
>     7. I think off_set_l[src_idx+1] here may happen index out of range when src_idx is max.
>        https://github.com/DyGRec/TGSRec/blob/9b61480db2a18a752a79f16df7bdd17c749cdd70/graph.py#L66
>        
>        help me please!!!


Hi @WhutTjk , I have several questions on the source code too. 

8. It did not sort the timestamp. Due to this `x[1]` index, it sorts the item index. It should be the `x[-1]`.
https://github.com/DyGRec/TGSRec/blob/9b61480db2a18a752a79f16df7bdd17c749cdd70/graph.py#L36

9. There are unsorted timestamps in `NeighborFinder` so that `find_before` does not work on purpose finding before time `cut_time`. In other words, it can not work binary searching without a sorting procedure.

https://github.com/DyGRec/TGSRec/blob/9b61480db2a18a752a79f16df7bdd17c749cdd70/graph.py#L87

For example, the returned timestamp values in `find_before()` are below:
```python
neighbors_ts[:left] - cut_time
#   > array([  0., 126., 127., -86.])
```
`find_before` can not return the smaller timestamp, because the result has the both positive and negative values.

If it has the sorted timestamp, the returned value has all the negative values like below:
```python
neighbors_ts[:left] - cut_time
# > array([-118., -118.,  -86.,  -34.,  -34.])
```

I've tried the experiment with the sorted timestamp, the MRR result has a huge gap compared to the reported MRR in the paper.

**Comment by zfan20** [comment]
Replies to @WhutTjk:

For questions 1, 2, 3, 5 and 7, please refer to our build-on-top method TGAT paper https://github.com/StatsDLMathsRecomSys/Inductive-representation-learning-on-temporal-graphs. They have clearer explanations on how the underlying code is working.

For question 4, the user and item embeddings are generated differently for different timestamps. The node_hist_embed is the initial user and item embeddings without involving any time information, which can be viewed as static preference representations of users and items.

For question 6, we focus on multi-next-steps recommendation instead of the standard next-item prediction for SASRec and BERT4Rec.


For @jeongwhanchoi 
It is not sorting the item index but the edge index. This is the same logit as TGAT paper.

**Comment by TangJiakai** [comment]
@zfan20 Yes, SASRec and BERT4Rec are for next-item prediction, but your paper still show the results of these models to campair with the TGSRec( and their metrics are so low), so could you explain about this please?

**Comment by zfan20** [comment]
Hi @WhutTjk,

For example, given a sequence [1,2,3,4,5, 6, 7, 8,9], with [1,2,3] as training, [4,5,6] as valid and [7,8,9] as test. We can still train SASRec and BERT4Rec with only [1,2,3] but when we do prediction for each step, such as to predict 8, in the inference stage, we use the input sequence [1,2,3,4,5,6,7] and to predict [9], we use [1,2,3,4,5,6,7,8]. 

Best.

**Comment by jeongwhanchoi** [comment]
@zfan20 please see [issue #6 on TGAT ](https://github.com/StatsDLMathsRecomSys/Inductive-representation-learning-on-temporal-graphs/issues/6#issuecomment-1005444775) .

**Comment by TangJiakai** [comment]
@jeongwhanchoi hello! I could not reproduce the result in this paper, and I also realize the algorithm LightGCN by PyG whose results are much better than TGSRec.....

**Comment by TangJiakai** [comment]
> @zfan20 please see [issue #6 on TGAT ](https://github.com/StatsDLMathsRecomSys/Inductive-representation-learning-on-temporal-graphs/issues/6#issuecomment-1005444775) .

In fact, the data has been processed so the index is sorted by timestamp. Howerver, I don't think temporal embedding has positive effect on results.....

**Comment by jeongwhanchoi** [comment]
@WhutTjk hello!

As a result of modifying the issue code and checking the model performance, I found that the MRR score on the ML-100k is significantly decreased to 0.0194. It is lower than LightGCN's MRR.

**Comment by jeongwhanchoi** [comment]
> > @zfan20 please see [issue #6 on TGAT ](https://github.com/StatsDLMathsRecomSys/Inductive-representation-learning-on-temporal-graphs/issues/6#issuecomment-1005444775) .
> 
> In fact, the data has been processed so the index is sorted by timestamp. Howerver, I don't think temporal embedding has positive effect on results.....

I've also checked the results using TGSRec without time embedding, but I have the same opinion as you in that time embedding is not an important component.

**Comment by TangJiakai** [comment]
> > > @zfan20 please see [issue #6 on TGAT ](https://github.com/StatsDLMathsRecomSys/Inductive-representation-learning-on-temporal-graphs/issues/6#issuecomment-1005444775) .
> > 
> > 
> > In fact, the data has been processed so the index is sorted by timestamp. Howerver, I don't think temporal embedding has positive effect on results.....
> 
> I've also checked the results using TGSRec without time embedding, but I have the same opinion as you in that time embedding is not an important component.

Yeah! Timestamp should have some positive influence on recommendation results, but the way of processing the timestamp in this paper may not be appropriate. And you know, just like Transformer and BERT, BERT only use simple position embedding but get nice effects....

**Comment by zfan20** [comment]
Hi,

Thanks for pointing out this update. We will update the code, redo the grid search again, and update new results as soon as possible. We are sorry for any inconvenience it may cause.

**Comment by jeongwhanchoi** [comment]
@zfan20 Thanks for your reply!
